package BackEnd;

import java.time.LocalDate;

/**
 * Exercise 1 Code
 * 
 * @author Nathan Jack
 * @version 1.0
 * @since Oct 9th, 2020
 * 
 *        Sources: Code requirements from assignment
 * 
 *        Description: Order object generated by user. Hold item information for
 *        order and prints PO to console.
 */
public class Order {
	private int orderID;
	private Item item;
	private String supplier;
	private LocalDate date;
	private String orderString = null;

	/**
	 * Constructor
	 * 
	 * @param item     Item object of tool to be ordered
	 * @param supplier supplier name from tool
	 * @param orderID  unique 5 digit hash generated by shopapp at time of order.
	 */
	public Order(Item item, String supplier, int orderID) {
		this.setItem(item);
		this.setSupplier(supplier);
		this.setDate();
		this.setOrderID(orderID);
		this.setOrderString();
	}

	public int getOrderID() {
		return orderID;
	}

	public void setOrderID(int orderID) {
		this.orderID = orderID;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getSupplier() {
		return supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	public LocalDate getDate() {
		return date;
	}

	/**
	 * Set date to todays date.
	 */
	public void setDate() {
		LocalDate now = LocalDate.now();
		this.date = now;

	}

	public String getOrderString() {
		return orderString;
	}

	/**
	 * Generates orderline string based on Order member variables
	 */
	public void setOrderString() {

		String valueAlignFormat = "| %-20s  %-27d |%n";
		String stringAlignFormat = "| %-20s  %-27s |%n";
		String res = String.format(valueAlignFormat, "ORDER ID:", this.getOrderID());
		res += String.format(stringAlignFormat, "Date Ordered:", this.getDate());
		res += String.format(stringAlignFormat, "", "");
		res += String.format(stringAlignFormat, "Item Description:", this.item.getToolName());
		res += String.format(valueAlignFormat, "Amount Ordered:", (50 - this.item.getQty()));
		res += String.format(stringAlignFormat, "Supplier:", this.getSupplier());
		res += "+*****************+*********+**********+***********+*";

		this.orderString = res;
	}

}
